version: "3.8"

x-common: &common
    logging:
        driver: "json-file"
        options:
            max-size: "500m"
            max-file: "5"
            compress: "true"
    networks:
        - main-network
    restart: on-failure

services:
    data:
        <<: *common
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes:
            - sqldata:/var/opt/mssql

    messages:
        <<: *common
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - 5672:5672
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmquser
            - RABBITMQ_DEFAULT_PASS=rabbitmqPassword12!
        volumes:
            - rabbitmq:/var/lib/rabbitmq/mnesia

    identity:
        <<: *common
        container_name: identity
        image: hristomanolov/carrentalsystem-identity-service:1.0
        build:
            context: ./Server
            dockerfile: ./CarRentalSystem.Identity/Dockerfile
        ports:
            - 5001:80
        env_file: Server/CarRentalSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentalIdentityDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - IdentitySettings__AdminPassword=adminpass12!
        volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        depends_on:
            - data

    dealers:
        <<: *common
        container_name: dealers
        image: hristomanolov/carrentalsystem-dealers-service:1.0
        build:
            context: ./Server
            dockerfile: ./CarRentalSystem.Dealers/Dockerfile
        ports:
            - 5002:80
        env_file:
            - Server/CarRentalSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentalDealersDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - ConnectionStrings__CronJobsConnection=Server=sqlserver;Database=CarRentalDealersCronJobsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        volumes:
            - ./.aspnet/dealers/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        depends_on:
            - data
            - messages

    statistics:
        <<: *common
        container_name: statistics
        image: hristomanolov/carrentalsystem-statistics-service:1.0
        build:
            context: ./Server
            dockerfile: ./CarRentalSystem.Statistics/Dockerfile
        ports:
            - 5003:80
        env_file:
            - Server/CarRentalSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CarRentalStatisticsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - ConnectionStrings__CronJobsConnection=Server=sqlserver;Database=CarRentalStatisticsCronJobsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        volumes:
            - ./.aspnet/statistics/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        depends_on:
            - data
            - messages

    notifications:
        <<: *common
        container_name: notifications
        image: hristomanolov/carrentalsystem-notifications-service:1.0
        build:
            context: ./Server
            dockerfile: ./CarRentalSystem.Notifications/Dockerfile
        ports:
            - 5004:80
        env_file:
            - Server/CarRentalSystem/Common.env
        environment:
            - NotificationSettings__AllowedOrigins=http://localhost
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        volumes:
            - ./.aspnet/notifications/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        depends_on:
            - messages

    client:
        container_name: client
        image: hristomanolov/carrentalsystem-user-client:1.0
        build:
            context: ./Client
            dockerfile: ./Dockerfile
            args:
                configuration: development
        ports:
            - 80:80
        restart: on-failure
        depends_on:
            - identity
            - dealers
            - statistics
            - notifications

    admin:
        <<: *common
        container_name: admin
        image: hristomanolov/carrentalsystem-admin-client:1.0
        build:
            context: ./Server
            dockerfile: ./CarRentalSystem.Admin/Dockerfile
        ports:
            - 5000:80
        env_file: Server/CarRentalSystem/Common.env
        environment:
            - ServiceEndpoints__Identity=http://identity
            - ServiceEndpoints__Dealers=http://dealers
            - ServiceEndpoints__Statistics=http://statistics
        volumes:
            - ./.aspnet/admin/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        depends_on:
            - identity
            - dealers
            - statistics

    watchdog:
        <<: *common
        container_name: watchdog
        image: hristomanolov/carrentalsystem-watchdog-service:1.0
        build:
            context: ./Server
            dockerfile: ./CarRentalSystem.Watchdog/Dockerfile
        ports:
            - 5500:80
        environment:
            - HealthChecks-UI__HealthChecks__0__Name=Identity
            - HealthChecks-UI__HealthChecks__0__Uri=http://identity/health
            - HealthChecks-UI__HealthChecks__1__Name=Dealers
            - HealthChecks-UI__HealthChecks__1__Uri=http://dealers/health
            - HealthChecks-UI__HealthChecks__2__Name=Statistics
            - HealthChecks-UI__HealthChecks__2__Uri=http://statistics/health
            - HealthChecks-UI__HealthChecks__3__Name=Notifications
            - HealthChecks-UI__HealthChecks__3__Uri=http://notifications/health
            - HealthChecks-UI__HealthChecks__4__Name=Admin
            - HealthChecks-UI__HealthChecks__4__Uri=http://admin/health
        depends_on:
            - identity
            - dealers
            - statistics
            - notifications
            - admin

networks:
    main-network:

volumes:
    sqldata:
    rabbitmq:
